blogapp/urls.py
from django.urls import path
from .views import *


app_name = "blogapp"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name='contact'),
    path("nepal/intro/", NepalView.as_view(), name="Nepal"),
    path("blog/list/", BlogListView.as_view(), name="bloglist"),
    path("event/list/", EventListView.as_view(), name="evenlist"),
    path("news/list/", NewsListView.as_view(), name="evenlist"),
    path("blog/<int:pk>/detail/", BlogDetailView.as_view(), name='blogdetail'),
    path("news/<int:pk>/detail/", NewsDetailView.as_view(), name="newsdetail"),
    path("blog/create/", BlogCreateView.as_view(), name='blogcreate'),
    path("blog/<int:pk>/update/", BlogUpdateView.as_view(), name='blogupdate'),
    path("blog/<int:pk>/delete/", BlogDeleteView.as_view(), name='blogdelete'),
    # path for all news
    path('news/create/', NewsCreateView.as_view(), name='newscreate'),
    path('news/<int:pk>/update/', NewsUpdateView.as_view(), name='newsupdate'),
    path('news/<int:pk>/delete/', NewsDeleteView.as_view(), name='newsdelete'),
    path('login/', LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path('category/<int:pk>/', CategoryDetailView.as_view(), name='categorydetail'),
    path('user/registration/', UserRegisteration.as_view(), name='userregistration'),
    path('blog/<int:pk>/comment', CommentView.as_view(), name='comment'),
    path("search/", SearchView.as_view(), name='search'),









]

blogproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("blogapp.urls")),

]
urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

templates/Nepal.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <br>
  <h1>I m from Nepal</h1>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>base</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <style type="text/css">
    
  </style>
</head>
<body class="container">
<!-- 	<a href="/">Home</a>
	<a href="/contact/">contact</a>
	<a href="/about/">about</a>
	<a href="/nepal/intro/">Nepal</a>
	<a href="/blog/list/">blog_list</a>
	<a href="/event/list/">event_list</a>
	<a href="/news/list/">news_list</a>
	<a href="/blog/create/">form</a> -->

<nav class="navbar navbar-expand-lg navbar-light bg-success">
  <!-- <a class="navbar-brand" href="#">MyBlog</a> -->
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
     
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="/contact/">contact <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="/about/">about<span class="sr-only">(current)</span></a>
      </li>
      <!--   <li class="nav-item active">
        <a class="nav-link" href="/nepal/intro/">Nepal <span class="sr-only">(current)</span></a>
      </li> -->
        <li class="nav-item active">
        <a class="nav-link" href="/blog/list/">blog_list <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="/event/list/">event_list <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/news/list/">news_list</a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="/blog/create/">blog_form<span class="sr-only">(current)</span></a>
      </li>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="/news/create/">news_form<span class="sr-only">(current)</span></a>
      </li>
        <form class="form-inline my-2 my-lg-0" action="/search/">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
          <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
        </form>
    </ul> 

  </div>
</nav>

        <li class="nav-item active">
          {% if request.user.is_authenticated %}
           <p class="text-dark">{{request.user}}</p>
           <a href="/logout/">Logout</a>
          {% else %} 
            <a href="/login/">login</a>
          {% endif %}  
          
         </li>
         <br>
         <a href="{% url 'blogapp:userregistration' %}">Register</a>
      






   
  {% block content %}
  {% endblock %}
</body>
</html>

templates/blogcreate.html
{% extends 'base.html' %}
{% load static %}
{%  block content %}
<div class="row">
	<div class="col-md-6">
		<h3>Add new blog</h3>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.as_p }}
			
		    <button>submit</button>
		</form>
    </div>
    <div class="col-md-6">

	    	{% for blog in blogs|slice:'2' %}
	    	<div class="row mt-2">
	    		<div class="col-md-6">
	    	       {{ blog.title|truncatechars:"10" }}
	    	    </div>
	    	    <div class="col-md-6">
	    	       
	    	    	<img src="{{blog.image.url}}" class="img-fluid">
	    	    </div>
   
	    	   
	    	</div>   
	    	{% endfor %}
	    
    </div>	

</div>
{% endblock %}

templates/categorydetail.html
{% extends 'base.html' %}
{%  load static %}
{% block content %}
 Category:<h3>{{categorys.title}}</h3>
 {% for news in categorys.relatednews.all %}
  <p>NEWS: <a href="{% url 'blogapp:newsdetail' news.id %}">{{news.title}}</a></p>
 {% endfor %}
 <!-- <img src="{{category.image.url}}" width="200px"> -->
{% endblock %}


 <!-- news_set.all -->

templates/comment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<form method = "POST">
		<br>
		{% csrf_token %}
		{{ form.as_p }}

	   <button class="btn btn-info">submit</button>	

	</form>
{% endblock %}

templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <br>
  <h1>Hello this is a contactpage</h1>
  <form method="POST">
  	{% csrf_token %}
  	{{ form.as_p }}
  	<button class="btn btn-success">submit</button>
  	
  </form>
{% endblock %}

templates/eventlist.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{%  for event in allevents %}
    <h1>{{ event.title }}</h1>
    <h2>{{ event.body }}</h2
{% endfor %}

{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <br>
  <h1>Hello this is a homepage</h1>
  <h5>{{django}}</h5>
  {% for blog in blogs %}
    <h5>{{blog.title}}</h5>
  {% endfor %}  
  <br>
   {% for event in events %}
    <h5>{{event.title}}</h5>
  {% endfor %}  
  <br>
  {% for category in categorylist %}
  <a href="{% url 'blogapp:categorydetail' category.id %}">{{category.title}}|</a>
  {% endfor %}
  <!-- {{request.user}} -->

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<br>
<style type="text/css">
	.login{
			text-align: center;

	}
	

</style>

{% if error %}
	<li class="text-danger">{{error}}</li>
{% endif %}	
 <form method = "POST">
 	{% csrf_token %}
	 <div class="login">
	    <h1>Login</h1>	
	 	{{ form.as_p }}
	 	<button>Login</button>
	 </div>	

 </form>
{% endblock %}

templates/newscreate.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<form method = "POST" enctype="multipart/form-data" id="user_form">
		<br>
		{% csrf_token %}
		{{ form.as_p }}

	   <button class="btn btn-primary">submit</button>	

	</form>
<script
  src="https://code.jquery.com/jquery-3.4.0.min.js"
  integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg="
  crossorigin="anonymous">

</script>
<script type="text/javascript">
	$(document).on('submit','#user_form',functioon(e){
		e.preventDefault();
		$.ajax({
			type:'POST'
			url = '/user/registration/'
		})
	})
	

</script>	
{% endblock %}

templates/newsdetail.html
{% extends 'base.html' %}
<!-- {%  load static %} -->
{% block content %}
   <h4>{{newsdetail.title}}</h4>
   <h4><li>{{newsdetail.category.image.url}}</li></h4>

   <h4>{{newsdetail.detail}}</h4>
   <img src="{{newsdetail.image.url}}">
   <h5>category:{{newsdetail.category}}</h5>
   <br>
   <h3>Related News</h3><hr>
   <p>you have visited this page {{newsdetail.visit_count}}</p>
   <div class="row">
   	{% for article in newsdetail.category.relatednews.all %}
   	    {% if article.id != newsdetail.id %}
	   	<div class="col-md-3">
	   		<a href="{% url 'blogapp:newsdetail' article.id %}"><h4>{{article.title}}</h4></a>
	   		<img src="{{article.image.url}}" class="img-fluid">
	   	
	   	</div>
	   	{% endif %} 	
   	
   </div>
   {% endfor %}

   <!-- {% for category in newsdetail.category.all %}
      <li>{{ category.title }}</li>
    {% endfor %} -->
    <a href="/news/{{newsdetail.pk}}/update/">Update</a>
    <a href="/news/{{newsdetail.pk}}/delete/">Delete</a>


{% endblock %}

templates/newslist.html
{% extends 'base.html' %}
{%  load static %}
{% block content %}
<br>
  {% for news in allnews %}
    <h3><a href="/news/{{news.id}}/detail/"> {{ news.title }}</a></h3>
    <img src="{{ news.image.url }}" width="200px";>
     {% for category in news.category.all %}
      {{ category.title }}
    {% endfor %}
   
   <hr>
  {% endfor %}
{% endblock %}

templates/searchresult.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>Search blogs</h3>
{% for blog in searchedblogs %}
  <li><a href="{% url 'blogapp:blogdetail' blog.id %}">{{blog.title}}</a></li>
  <p>{{blog.content|truncatewords:'20'}}</p>
{% empty %}
<h3>no blogs found</h3>

{% endfor %}
{% for news in searchednews %}
   <li><a href="{% url 'blogapp:newsdetail' news.id %}">{{news.title}}</a></li>
   <p>{{news.category}}</p>
{% endfor %}
{% endblock %}

templates/userregistertion.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<form method = "POST">
		<br>
		{% csrf_token %}
		{{ form.as_p }}

	   <button class="btn btn-info">submit</button>	

	</form>
{% endblock %}